### PR TITLE
feat: expand the definition with more examples

### PR DESCRIPTION
**Pull request by ivana-isadora**
Added examples for:

- discriminator usage
- deprecated parameter and operation
- x-tagGroups
- x-webhooks
- `delete` and `post` operations
- `nullable`
- recursive property
- object within object

To add:

- callback
- examples for content type x-www-form-encoded and octet-stream
- oneOf example
- XML schemas
- x-traitTag and x-summary usage examples
- better response examples

### CODE REVIEW

**Comment by adamaltman** [comment]
This is great. Needs to be updated for 3.1. Not sure how I never saw this PR. 🙈

**Comment by ivana-isadora** [comment]
Hi @lornajane I just got a notification about this PR. Is there anything I should do here?

**Comment by lornajane** [comment]
Hi @ivana-isadora !! I'm working to get this old PR merged, thanks for adding all these examples for us, you are a star!

**Comment by ivana-isadora** [comment]
> Hi @ivana-isadora !! I'm working to get this old PR merged, thanks for adding all these examples for us, you are a star!

Thank you for picking it up! If there's anything I can do to help, just let me know.

**Review by lornajane — APPROVED** [review]
Thanks again @ivana-isadora !

**Pull request merged**
