### PR TITLE
chore: rename .redocly.yaml to redocly.yaml

### PR DESCRIPTION
**Pull request by adamaltman**
## What/Why/How?

The dot file is hidden by default on some operating systems which makes it harder to access for some people.

Cons:
- The dot arranges it alphabetically near the top.

Pros:
- This isn't unprecedented (see `package.json`).

## Reference

- https://redocly.com/docs/cli/changelog/#100-beta86-2022-03-09

## Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### CODE REVIEW

**Review by RomanHotsiy — APPROVED** [review]

**Comment by javierjulio** [comment]
For the v2 upgrade guide, I think it's worth calling this out at the top of the breaking changes section on its own. I kept seeing the "No APIs were provided." error despite making several of the changes documented in the guide. My issue was I still had the config file as `.redocly.yaml` instead of `redocly.yaml`. I used this starter package as I'm sure many others have too so to save some grief that would help. Thank you!

**Comment by RomanHotsiy** [comment]
cc @tatomyr  

Thanks, @javierjulio

**Comment by tatomyr** [comment]
It's in the top of the migration checklist: https://redocly.com/docs/cli/guides/migrate-to-v2#migration-checklist

Maybe it's worth highlighting the guide somehow? Would it help if we add the link to it in the Redocly CLI README?

**Comment by javierjulio** [comment]
@tatomyr I see the change from https://github.com/Redocly/redocly-cli/pull/2231 on the live page and I think that's helpful., thanks!

**Pull request merged**
